//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model2.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        internal static string between {
            get {
                return ResourceManager.GetString("between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billion.
        /// </summary>
        internal static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;currencies&quot;:[{&quot;code&quot;:&quot;AFN&quot;,&quot;name&quot;:&quot;Afghan afghani&quot;,&quot;symbol&quot;:&quot;؋&quot;}],&quot;name&quot;:&quot;Afghanistan&quot;,&quot;capital&quot;:&quot;Kabul&quot;,&quot;population&quot;:27657145},{&quot;currencies&quot;:[{&quot;code&quot;:&quot;EUR&quot;,&quot;name&quot;:&quot;Euro&quot;,&quot;symbol&quot;:&quot;€&quot;}],&quot;name&quot;:&quot;Åland Islands&quot;,&quot;capital&quot;:&quot;Mariehamn&quot;,&quot;population&quot;:28875},{&quot;currencies&quot;:[{&quot;code&quot;:&quot;ALL&quot;,&quot;name&quot;:&quot;Albanian lek&quot;,&quot;symbol&quot;:&quot;L&quot;}],&quot;name&quot;:&quot;Albania&quot;,&quot;capital&quot;:&quot;Tirana&quot;,&quot;population&quot;:2886026},{&quot;currencies&quot;:[{&quot;code&quot;:&quot;DZD&quot;,&quot;name&quot;:&quot;Algerian dinar&quot;,&quot;symbol&quot;:&quot;د.ج&quot;}],&quot;name&quot;:&quot;Algeria&quot;,&quot;capital&quot;:&quot;Algiers&quot;,&quot;population&quot;:40400000},{&quot;cu [rest of string was tru....
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P=104.
        /// </summary>
        internal static string city_tag {
            get {
                return ResourceManager.GetString("city_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /F.
        /// </summary>
        internal static string closeCity {
            get {
                return ResourceManager.GetString("closeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /TEXT.
        /// </summary>
        internal static string closeText {
            get {
                return ResourceManager.GetString("closeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollars.
        /// </summary>
        internal static string dollars {
            get {
                return ResourceManager.GetString("dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hundred.
        /// </summary>
        internal static string hundred {
            get {
                return ResourceManager.GetString("hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to million.
        /// </summary>
        internal static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        internal static string openText {
            get {
                return ResourceManager.GetString("openText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        internal static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percentage.
        /// </summary>
        internal static string percentage {
            get {
                return ResourceManager.GetString("percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\s|^)([0-9])+/([0-9])+(\s|$).
        /// </summary>
        internal static string regex_Fraction {
            get {
                return ResourceManager.GetString("regex_Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9])+([.][0-9]+)*$.
        /// </summary>
        internal static string regex_Numbers {
            get {
                return ResourceManager.GetString("regex_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^|[0-1][0-2]|[1-9])(P|A)M$.
        /// </summary>
        internal static string regex_PM_AM {
            get {
                return ResourceManager.GetString("regex_PM_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([0-1][0-2]|[1-9])(P|A)M$.
        /// </summary>
        internal static string regex_PM_AM_withHoursOnly {
            get {
                return ResourceManager.GetString("regex_PM_AM_withHoursOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thousand.
        /// </summary>
        internal static string thousand {
            get {
                return ResourceManager.GetString("thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trillion.
        /// </summary>
        internal static string trillion {
            get {
                return ResourceManager.GetString("trillion", resourceCulture);
            }
        }
    }
}
